version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - ./data/mysql:/var/lib/mysql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27019:27017'
    volumes:
      - ./data/mongo:/data/db


  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
