name: Docker Build&Push Server CI

on:
  push:
    branches:
      - "release"
    paths:
      - "evento/evento-server/version.json"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get current version
        uses: dolittle/read-version-from-file-action@v2
        with:
          path: evento-server/version.json
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file docker/evento-server/Dockerfile --tag eventoframework/evento-server:latest --tag eventoframework/evento-server:${{ current-version }}

      - name: Push the Docker image
        run: docker push --all-tags eventoframework/evento-server

