name: Maven Build&Push Repository

on:
  push:
    branches:
      - "zzz"
    #paths:
    #  - "evento-server/version.json"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Enable Gradle
        run: chmod +x gradlew

      - name: Publish
        run: ./gradlew publish
